version: 2

build:
        os: ubuntu-20.04
        tools:
                python: "mambaforge-4.10"

conda:
        environment: build-env.yml

mkdocs:
        configuration: mkdocs.yml
        fail_on_warning: false
