name: dadi-cli-gpu
channels:
  - conda-forge
  - bioconda
  - nvidia
dependencies:
  - cuda
  - cyvcf2
  - dadi
  - demes
  - dill
  - matplotlib
  - ndcctools
  - nlopt
  - numpy
  - pip
  - pycuda
  - python==3.9
  - scipy
  - pip:
      - scikit-cuda
      - .
