name: dadi-cli-gpu
channels:
  - conda-forge
  - bioconda
  - nvidia
dependencies:
  - cuda
  - gcc
  - gfortran
  - gxx==11.3
  - demes
  - dill
  - matplotlib
  - ndcctools
  - nlopt
  - numpy
  - pip
  - pycuda
  - scipy
  - pip:
      - dadi>2.1.0
      - scikit-cuda
      - .
