name: dadi-cli-cpu
channels:
  - conda-forge
  - bioconda
dependencies:
  - cyvcf2
  - dadi
  - demes
  - dill
  - matplotlib
  - ndcctools
  - nlopt
  - numpy
  - pip
  - python==3.9
  - scipy
  - pip:
      - .
